Доработана функциональность по ТЗ спринта 6 #1
iGladkikh/java-kanban pull request #2
Opened 2024-03-18 13:33 UTC by iGladkikh

2024-03-18 17:02 UTC, Yang-Pi requested changes

2024-03-18 17:02 UTC, Yang-Pi commented on src/services/InMemoryHistoryManager.java
> +        this.history = new LinkedHashMap<>();
Все верно, только класс связного списка должен быть не из библиотеки java.util, а самописный)

2024-03-18 17:02 UTC, Yang-Pi commented on src/services/InMemoryTaskManager.java
> +        epics.put(epicId, epic.copy());
Лишняя операция на самом деле, понимаю твою идею, но сам объект - это фактически модель данных, полученная по API (далее вы именно это и будете делать)

2024-03-19 09:28 UTC, iGladkikh commented on src/services/InMemoryTaskManager.java
> +        epics.put(epicId, epic.copy());
Исправлено. Спасибо!

2024-03-19 09:29 UTC, iGladkikh commented on src/services/InMemoryHistoryManager.java
> +        this.history = new LinkedHashMap<>();
Исправлено. Спасибо!

2024-03-19 16:56 UTC, Yang-Pi requested changes

2024-03-19 16:56 UTC, Yang-Pi commented on src/services/InMemoryHistoryManager.java
> +        result.add(node.data);
node вполне мб null, поэтому получишь NPE тут

2024-03-19 16:56 UTC, Yang-Pi commented on src/services/InMemoryHistoryManager.java
> +        return result;
По ТЗ список задач нужно вернуть в том порядке, как они добавлялись, у тебя же он обратный

2024-03-19 16:56 UTC, Yang-Pi commented on src/services/InMemoryHistoryManager.java
> +    private Node last;
Рекомендую все же добавить еще и голову списка (head & tail или first & last)

2024-03-20 08:28 UTC, iGladkikh commented on src/services/InMemoryHistoryManager.java
> +    private Node last;
Добавлено поле Node first.

2024-03-20 08:28 UTC, iGladkikh commented on src/services/InMemoryHistoryManager.java
> +        return result;
Исправлено.

2024-03-20 08:46 UTC, iGladkikh commented on src/services/InMemoryHistoryManager.java
> +        result.add(node.data);
Исправлено. Дополнена проверка в стр. 44. Спасибо!

2024-03-20 15:20 UTC, Yang-Pi approved these changes

2024-03-20 15:20 UTC, Yang-Pi commented on src/services/InMemoryHistoryManager.java
> +        while (node.hasNext()) {
Работает, но сложно)
```
Node tmp = first;
while (tmp != null) {
...
tmp = tmp.next();
}
```

2024-03-21 07:30 UTC, iGladkikh commented on src/services/InMemoryHistoryManager.java
> +        while (node.hasNext()) {
Исправлено.

2024-03-21 07:30 UTC, merged