Доработана функциональность по ТЗ спринта 7
iGladkikh/java-kanban pull request #3
Opened 2024-03-28 13:13 UTC by iGladkikh

2024-03-28 17:04 UTC, Yang-Pi requested changes

2024-03-28 17:04 UTC, Yang-Pi commented on src/services/FileBackedTaskManager.java
> +    public static String historyToString(HistoryManager manager) {
Слишком широкий модификатор доступа у метода (и у двух ниже)

2024-03-28 17:04 UTC, Yang-Pi commented on src/services/FileBackedTaskManager.java
> +                        addEpic(epic);
Обрати внимание, что внутри методов add*() вызывается логика сохранения, те при загрузки задач из файла задачи в этот же файл одновременно и сохраняются.

2024-03-28 17:04 UTC, Yang-Pi commented on src/services/FileBackedTaskManager.java
> +                        Task task = Task.createFromString(taskData, DATA_FILE_DELIMITER);
Важный момент - для задач был задан id, но затем при создании новых будет id cнова генерироваться, но при текущей реализации эта генерация будет с нуля, что приведет к дублированию.

2024-03-29 06:21 UTC, iGladkikh commented on src/services/FileBackedTaskManager.java
> +    public static String historyToString(HistoryManager manager) {
Удален модификатор "public". Спасибо!

2024-03-29 06:24 UTC, iGladkikh commented on src/services/FileBackedTaskManager.java
> +                        addEpic(epic);
Исправлено на вызов методов "super.add*()". Спасибо!

2024-03-29 06:26 UTC, iGladkikh commented on src/services/FileBackedTaskManager.java
> +                        Task task = Task.createFromString(taskData, DATA_FILE_DELIMITER);
Внесены дополнения в логику конструктора класса Task. Спасибо!

2024-03-29 17:17 UTC, Yang-Pi approved these changes

2024-03-29 17:57 UTC, merged