Доработать функциональность по ТЗ спринта 8:
iGladkikh/java-kanban pull request #4
Opened 2024-04-12 12:47 UTC by iGladkikh

1. Добавить поля startTime и duration, prioritizedTasks.
2. Добавить проверка пересечений задач по времени.
3. Дополнить тесты.

2024-04-13 12:46 UTC, Yang-Pi requested changes

2024-04-13 12:46 UTC, Yang-Pi commented on src/tasks/Task.java
> +    public boolean isPrioritized() {
Не совсем понял идею этого метода, потому что, например, он также распространяется и на epic. Добавлять задачи в коллекцию prioritizedTasks можно и с null в качестве времени начала, достаточно добавить в обработчик сортировки опцию nullsLast

2024-04-13 12:46 UTC, Yang-Pi commented on src/tasks/Task.java
> +        } catch (NullPointerException e) {
Это анти-паттерн, проверку на null лучше всего делать через обычный if, в этом же случае можно использовать и тернарный оператор

2024-04-13 12:46 UTC, Yang-Pi commented on test/services/TaskManagerTest.java
> +    public void ShouldBeImpossibleToAddTaskWhenTheDatesIntersects() {
название тестов, как и методов, пишется с маленькой буквы

2024-04-13 12:46 UTC, Yang-Pi commented on test/services/TaskManagerTest.java
> +        assertEquals(4, taskManager.getTasks().size());
Вот эти ассерты не нужны в этом тесте, потому что проверяется именно функционал для taks5 и task6

2024-04-13 12:49 UTC, Yang-Pi commented on src/services/InMemoryTaskManager.java
> +    private void computeEpicFields(Epic epic) {
Еще у эпика нужно обновлять duration

2024-04-13 19:08 UTC, iGladkikh commented on src/tasks/Task.java
> +        } catch (NullPointerException e) {
Исправлено (примене тернарный оператор). Спасибо!

2024-04-13 19:09 UTC, iGladkikh commented on test/services/TaskManagerTest.java
> +    public void ShouldBeImpossibleToAddTaskWhenTheDatesIntersects() {
Исправлено. Спасибо!

2024-04-13 19:16 UTC, iGladkikh commented on test/services/TaskManagerTest.java
> +        assertEquals(4, taskManager.getTasks().size());
Исправлено. Спасибо!

2024-04-13 20:28 UTC, iGladkikh commented on src/tasks/Task.java
> +    public boolean isPrioritized() {
Удалено (из ТЗ: "Дата начала задачи по каким-то причинам может быть не задана. Тогда при добавлении её не следует учитывать в списке задач и подзадач, отсортированных по времени начала. Такая задача не влияет на приоритет других, а при попадании в список может сломать логику работы компаратора").

2024-04-13 20:43 UTC, iGladkikh commented on src/services/InMemoryTaskManager.java
> +    private void computeEpicFields(Epic epic) {
Обновление поля duration дополнено (стр. 70). Учитывая, что duration будет задано, поле endTime из класса Epic удалено (как вычисляемое).

2024-04-14 09:56 UTC, Yang-Pi commented on src/services/InMemoryTaskManager.java
> +    private void computeEpicFields(Epic epic) {
А вот это не совсем верно. Потому что тут немного странное требование ТЗ, но все требование
"Продолжительность эпика — сумма продолжительности всех его подзадач".
Что это значит? а то, что end time для эпика вполне может не быть равным start time + duration

2024-04-14 12:11 UTC, iGladkikh commented on src/services/InMemoryTaskManager.java
> +    private void computeEpicFields(Epic epic) {
Исправлено. Поле endTime в классе Epic возвращено. Спасибо за терпение! :)

2024-04-15 11:18 UTC, Yang-Pi approved these changes

2024-04-15 11:54 UTC, merged